require('dotenv').config();
const express = require('express');
const app = express();

const keywords = [
    "เรารักสถาบันพระมหากษัตรีย์",
    "ทรงพระเจริญ",
    "ทักษิณ",
    "ก้าวไกล",
    "เพื่อไทย",
    "พิธา",
    "สมรสเท่าเทียม",
    "ประชุมสภา",
    "บิ๊กต่อ",
    "บิ๊กโจ๊ก",
    "การเมือง",
    "รัฐบาล",
    "ข่าววันนี้",
    "สมเด็จพระเทพ",
    "พระราชินีสุทิดา",
    "ม112",
    "ภาษีประชาชน",
    "ลุงตู่",
    "นิรโทษกรรม",
    "ทะลุวัง",
    "ด้อมส้ม",
    "พระราชกรณียกิจ",
    "เกณฑ์ทหาร",
    "รัฐประหาร",
    "ล้มล้างการปกครอง",
    "ปฏิรูปกองทัพ",
    "รัชกาลที่ 10",
    "รักในหลวง",
    "นายกรัฐมนตรี",
    "ศาลรัฐธรรมนูญ",
    "กลาโหม",
    "ทหารมีไว้ทำไม",
    "กองทัพ",
    "ยุทโธปกรณ์",
    "อาวุธ",
    "รถถัง",
    "ช่วยเหลือประชาชน",
    "เรือดำน้ำ",
    "เรือรบ",
    "เครื่องบินรบ",
    "ยกเลิก 112",
    "ตะวัน แบม",
    "ภาษีกู",
    "ยืนหยุดขัง",
    "ชุมนุมประท้วง",
    "PM2.5",
    "น้ำท่วม",
    "รถติด",
    "เว็บพนัน",
    "ยาเสพติด",
    "สงคราม",
    "สถาบัน",
    "กองทัพบก",
    "covid19",
    "บุคคล",
    "องค์กร",
    "ทั่วไป",
    "ตำรวจ",
    "ความเชื่อมั่น TIJ",
    "DSI",
    "การท่องเที่ยวประเทศไทย",
    "พลังประชารัฐ",
    "สถาบันฯ - ต่อต้าน",
    "สถาบันฯ - สนับสนุน",
    "นัดหมายชุมนุม",
    "ยุยงให้เกิดความรุนแรง",
    "ความมั่นคง",
    "คุณภาพชีวิตประชาชน",
    "3 จังหวัดชายแดนใต้",
    "ธงชาติไทย",
    "โกงเงิน",
    "กสทช",
    "กูให้มึงอยู่ใต้รัฐธรรมนูญ",
    "เกาะกูด",
    "The101world",
    "Mono29tv",
    "THESTATESTIMES",
    "VOAThai",
    "WorkpointNews23",
    "thaigovernment",
    "thebetternews",
    "MorningNewsTV3",
    "Ejan",
    "ThaipostTV",
    "PRbangkok",
    "nationstoryTH",
    "chiangmainews7906",
    "newsnbt2hd",
    "3PlusNews",
    "FM91TrafficPro",
    "matichontv",
    "Posttoday_Official",
    "TheActive",
    "TheMATTERco",
    "TheReportersTH",
    "SiamrathOnline",
    "one31official",
    "BBCThai",
    "PPTVHD36",
    "historyworld45",
    "KhaosodTV",
    "KOMCHADLUEK",
    "RoyalThai830",
    "TV5HDONLINE",
    "onenews31",
    "SiamnewsOfficial",
    "NextForward77",
    "CH7HDNEWS",
    "MatichonWeekly",
    "honekrasaeofficial",
    "user-bh4mu3sd8z",
    "gunjompalangchannel",
    "2020ENTERTAINMENT",
    "SPYChannelTV",
    "kuizapbunterng",
    "wassanananuam3236",
    "LM.channel",
    "user-vx1ct3tk2h",
    "Tourlong",
    "77kaoded",
    "tvpoolofficial",
    "thaich8news",
    "nationworldnews8968",
    "PaTedTalk",
    "TheThaiger_TH",
    "TodayVariety2024",
    "a-channel",
    "Valor_Tactical_Thailand",
    "user-uk4nh4eg8w",
    "FNDiary",
    "TanlokeThaiPBS",
    "KNDStudio",
    "channel-SAYLOOY.TH.",
    "bluephoenix7540",
    "psil61",
    "prachatai",
    "NavyChannelTH",
    "KHUNDONG",
    "MGRonlinevdo",
    "esnews99",
    "ThaiMoveInstitute_TH",
    "GMM25Thailand",
    "SaRaDee_Ch",
    "apinews22",
    "ruuwai",
    "GetterAirforce",
    "royalthainavy-officialchannel",
    "TOJOchannel",
    "carabaoofficial",
    "LisasWorldd",
    "suthichailive",
    "NKoios321",
    "NetflixThailand",
    "insidethailand",
    "user-gw3sj9tp8q",
    "bangkokbiznewsthailand",
    "KaohoonTVOnline",
    "PointofView",
    "ratsadonnews",
    "TheSecretSauceTH",
    "ThaiPBSNews",
    "TNN.Online",
    "onebunterngofficial",
    "PaulPattarapon",
    "Sawfon22",
    "NineEntertainMCOT",
    "MoneyChat",
    "nuttapumin",
    "sondhitalk",
    "9MCOT",
    "wos1999",
    "ninenews9",
    "MicroStrategy-Crypto-Corp",
    "sorrayuth9115",
    "POPAPANDA",
    "PiSecurities",
    "carabaovdo",
    "LegendaryChannel369",
    "MCOTNewsFM100.5",
    "TOPDARA",
    "rtafchannel4622",
    "tnamcot",
    "TheStandardNews",
    "the.peoples.of.thailand",
    "TheStandardPodcast",
    "thinkingradio",
    "Thaich8",
    "avengersfilmmakingstudio4238",
    "PAEfromYNW",
    "ThaiPBS",
    "jaysamongkon",
    "commentjung",
    "unitedthaination",
    "SinghahaChannel",
    "Khaosueb",
    "isranewsagency",
    "progressivethai",
    "sirotetalk",
    "TV24Original",
    "ARAICHANAL",
    "therepublic2020",
    "InfoQuestNews",
    "Luichonkhao",
    "SpokeDarkTV",
    "PolicetvUCIMEDIA",
    "Thai_Weapon_Channel",
    "nailname",
    "thaitv2475",
    "user-ly8he1vv3o",
    "buddylawyer",
    "voicetv",
    "SNIPERNEWs",
    "Mii-up777",
    "pigkaploy",
    "Hotnews106",
    "Jomquan",
    "sanirojthumayos",
    "FastNews1996",
    "COINERCH",
    "TODAYNEWSTH",
    "ThaiNews-online",
    "TalkZik",
    "Thaiarmedforcecom",
    "noocchanel",
    "SOLDIERsACTIVITY",
    "PudProduction",
    "KhaosodTV",
    "DailyTopicsTH",
    "AMARINTVHD",
    "thaimilitary6653",
    "AssavarakChannel",
    "FriendsTalkChannel",
    "Progresspeopletravel",
    "ceotalklive",
    "thairathonline",
    "prachaya_nongnuch",
    "trendyworld77",
    "thandigital",
    "brighttv20",
    "TOPNEWS_TH",
    "traderkp",
    "-futureforward7049",
    "THNEWSOK",
    "TOPNEWSLIVE77",
    "todayth",
    "thaihotnews",
    "NaewnaOnline",
    "mingmin_ch",
    "ringside578",
    "INNNEWS_INN",
    "DailynewsOnlineOfficial",
    "JS100RadioOFFICIAL",
    "thebangkokinsight1552",
    "พลเอกประยุทธ์ จันทร์โอชา",
    "ลุงป้อม",
    "รองนายก",
    "หนูกัญชา",
    "รัฐมนตรีแป้ง",
    "อนุพงษ์ เผ่าจินดา",
    "โฆษกศบค.",
    "ปิยบุตร",
    "สส.พิธา",
    "นายกโซเชียล",
    "ช่อพรรณิการ์",
    "วิโรจน์ ลักขณาอดิศร",
    "นางอมรรัตน์",
    "รังสิมันต์ โรม",
    "วทันยา วงษ์โอภาสี",
    "สส.ไพบูลย์",
    "สส.อภิสิทธิ์",
    "ชวน หลีกภัย",
    "พลังประชารัฐ",
    "ภูมิใจไทย",
    "เพื่อไทย",
    "อนาคตใหม่",
    "คนไทยรักในหลวง",
    "พัฒนาเศรษฐกิจ",
    "ปรับปรุงที่ดิน",
    "สาธารณสุข",
    "การจัดการภาครัฐ",
    "ป้องกันการทุจริต",
    "เบี้ยยังชีพคนพิการ",
    "คนละครึ่ง",
    "ประกันรายได้",
    "ค่าแรงขั้นต่ำ",
    "เรียนทางไกล",
    "โครงการความโปร่งใสในการก่อสร้างภาครัฐ",
    "สันติสุขชายแดนใต้",
    "รัฐบาลดิจิทัล",
    "ชป.สู้ภัยแล้ง",
    "คณะกรรมการแก้ไขรัฐธรรมนูญ",
    "เศรษฐกิจพัง",
    "แก้รัฐธรรมนูญ",
    "ทรัพย์สินส่วนพระมหากษัตริย์",
    "ยกเลิก112",
    "ประยุทธ์ออกไป",
    "จะแต่งอะไรมันก็เรื่องของกู",
    "เบี้ยยังชีพ",
    "หยุดนิคมอุตสาหกรรม",
    "ปฏิรูปกษัตริย์",
    "หยุดคุกคามประชาชน",
    "ATMG",
    "FN Scar-L",
    "สไตเกอร์",
    "AH-1F Cobra",
    "ทหารช่วยประชาชน",
    "ทหารพันธุ์ดี",
    "ซื้ออาวุธ",
    "ปรับปรุงเกณฑ์ทหาร",
    "ทหารปฏิวัติ",
    "สมัครนายสิบ",
    "ทหารรับเงิน",
    "ยึดยาบ้า",
    "ลงทะเบียนแรงงานต่างด้าว",
    "กระบวนการค้ามนุษย์",
    "ทำลายข้าวของ",
    "กลุ่มผู้ร้าย",
    "อาชญากรรมข้ามชาติ",
    "สินค้าบุหรี่นำเข้าจากฟิลิปปินส์",
    "ละเมิดลิขสิทธิ์",
    "ตัดไม้ทำลายป่า",
    "ควบคุมมลพิษ",
    "วัคซีนฟรี",
    "วัคซีนปลอม",
    "ฝึกวิชาชีพ",
    "ทหารเมา",
    "IOทหาร",
    "เสี่ยโอป่วย",
    "ฉีดวัคซีนเมกา",
    "ทหารเสพยา",
    "Parit Chiwarak",
    "อานนท์ นำภา",
    "ไผ่ดาวดิน",
    "ไมค์ ระยอง",
    "พังรุ้ง",
    "ชาญวิทย์",
    "ไฟป่า",
    "หมอกควัน",
    "เกษตรชุมชน",
    "ซาร์ยีด",
    "พระบาทสมเด็จพระเจ้าอยู่หัวมหาภูมิพลอดุลยเดชมหาราช",
    "สิริกิตต์",
    "รัชกาลที่10",
    "พระเทพ",
    "ราชินีสุทิดา",
    "เจ้าฟ้าพัชรกิติยาภา",
    "สิริวัณวรี",
    "ทีปังกร",
    "หม่อมก้อย",
    "ข่มขืน",
    "ไฟดับ",
    "น้ำป่า",
    "หลังคาปลิว",
    "ดินสไล",
    "หากู้เงิน",
    "ฝึกอบรม",
    "เชค min",
    "กากายะอ์ฟัร",
    "ธรรมนิติ",
    "มัสยิดรูฮุลอร์",
    "PNYS",
    "The Patani",
    "Permas",
    "สถาบันส่งเสริมการศึกษาและวิจัยเกี่ยวกับอิสลาม",
    "มัสยิดอิหม่ามฮุเซ็นละงู",
    "กองทัพบกช่วยเหลือประชาชน",
    "กองกำลังป้องกันชายแดน",
    "Israel",
    "อเมริกา",
    "อีรอน",
    "ฟาลัสติน",
    "วัคซีนดีๆ",
    "ivf",
    "ล้มราชวงศ์",
    "ไม่มีอาชีพ",
    "ทักกี้",
    "ตำรวจไทย",
    "RESTART DEMOCRACY",
    "กลุ่มทะลุฟ้า",
    "ทะลุแก๊ส thalugaz",
    "btc",
    "pancakeswap",
    "ไทยพานิชย์",
    "ผู้ต้องหา",
    "ไกล่เกลี่ย",
    "กฤษฎีกา",
    "แชร์ออนไลน์",
    "โทนี่ วู้ดซัม",
    "อีปู",
    "พปชร",
    "ถวายพระพร",
    "พรรคชาติพัฒนากล้า",
    "เสรีรวมไทย",
    "เปลี่ยนธงชาติใหม่",
    "ริบบิ้นธงชาติ",
    "ชาติคือ",
    "ภูมิใจที่ได้เป็นทหาร",
];

let index = 0; // เริ่มต้นที่ลำดับที่ 0

app.get('/api/keywords', (req, res) => {
    const keywordObject = {
        keyword_number : index + 1, // ลำดับของคำศัพท์ (เริ่มต้นที่ 1)
        keyword: keywords[index] // คำศัพท์ที่ส่งออก
    };

    res.json(keywordObject);

    index++;

    if (index >= keywords.length) {
        index = 0;
    }
});

app.listen(process.env.PORT, () => {
    console.log("Server is running on port", process.env.PORT);
});
